const kMouseCursorHeight:usize=24;
pub static MOUSE_CURSOR_SHAPE:[&[u8]; kMouseCursorHeight] =[
    "@              ".as_bytes(),
    "@@             ".as_bytes(),
    "@.@            ".as_bytes(),
    "@..@           ".as_bytes(),
    "@...@          ".as_bytes(),
    "@....@         ".as_bytes(),
    "@.....@        ".as_bytes(),
    "@......@       ".as_bytes(),
    "@.......@      ".as_bytes(),
    "@........@     ".as_bytes(),
    "@.........@    ".as_bytes(),
    "@..........@   ".as_bytes(),
    "@...........@  ".as_bytes(),
    "@............@ ".as_bytes(),
    "@......@@@@@@@@".as_bytes(),
    "@......@       ".as_bytes(),
    "@....@@.@      ".as_bytes(),
    "@...@ @.@      ".as_bytes(),
    "@..@   @.@     ".as_bytes(),
    "@.@    @.@     ".as_bytes(),
    "@@      @.@    ".as_bytes(),
    "@       @.@    ".as_bytes(),
    "         @.@   ".as_bytes(),
    "         @@@   ".as_bytes(),
];