[package]
name = "xhci"
version = "0.1.0"
edition = "2021"

[dependencies]
accessor = "0.3.3"
bit_field = "0.10.2"
paste = "1.0.15"
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false }